variables:
  GIT_SUBMODULE_STRATEGY: recursive
  S3_BUCKET_NAME: "suzanne.link"

stages: 
  - test
  - build
  - deploy

cache:
  paths:
    - public

test:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  stage: test
  except:
    - main    
  before_script:
    - apk add --update --no-cache git    
  script:
    - hugo

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  stage: build
  only:
    - main
  before_script:
    - apk add --update --no-cache git
  script:
    - hugo
  artifacts:
    paths:
      - public    

s3:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  only:
    - main
  script:
    - aws s3 sync public s3://$S3_BUCKET_NAME